/**
 * Teaches the generated Android Gradle project to sign release builds with the
 * project keystore (AP-7, C-30).
 *
 * `src-tauri/gen/android/` is build output, regenerated by `tauri android init`
 * on every CI run, so this patch has to be reapplied each time rather than
 * committed. It is idempotent and fails loudly when the Tauri template changes
 * shape — a silently unsigned APK cannot install over the previous version,
 * which would break every user's upgrade path without any error at build time.
 *
 * Reads `src-tauri/gen/android/keystore.properties` at build time:
 *
 *     storeFile=release.jks
 *     storePassword=…
 *     keyAlias=…
 *     password=…
 *
 *     node scripts/patch-android-signing.ts
 */

import fs from 'node:fs'
import path from 'node:path'

const gradleFile = path.resolve('src-tauri/gen/android/app/build.gradle.kts')

if (!fs.existsSync(gradleFile)) {
  console.error(`patch-android-signing: ${gradleFile} not found — run \`tauri android init\` first`)
  process.exit(1)
}

let source = fs.readFileSync(gradleFile, 'utf8')

if (source.includes('signingConfigs.getByName("release")')) {
  console.log('patch-android-signing: already patched')
  process.exit(0)
}

const IMPORTS = 'import java.io.FileInputStream\nimport java.util.Properties\n'

const SIGNING_CONFIG = `
    signingConfigs {
        create("release") {
            val keystorePropertiesFile = rootProject.file("keystore.properties")
            val keystoreProperties = Properties()
            if (keystorePropertiesFile.exists()) {
                keystoreProperties.load(FileInputStream(keystorePropertiesFile))
            }
            keyAlias = keystoreProperties["keyAlias"] as String
            keyPassword = keystoreProperties["password"] as String
            storeFile = file(keystoreProperties["storeFile"] as String)
            storePassword = keystoreProperties["storePassword"] as String
        }
    }
`

function fail(what: string): never {
  console.error(`patch-android-signing: could not find ${what} in ${gradleFile}.`)
  console.error('The Tauri Android template has changed; update this script before releasing.')
  process.exit(1)
}

// 1. Imports go above the plugins block, which is always the first statement.
const pluginsAt = source.indexOf('plugins {')
if (pluginsAt < 0) fail('the `plugins {` block')
source = `${IMPORTS}${source.slice(0, pluginsAt)}${source.slice(pluginsAt)}`

// 2. The signing config itself, just inside `android { … }`.
const androidAt = source.indexOf('\nandroid {')
if (androidAt < 0) fail('the `android {` block')
const androidBraceEnd = source.indexOf('{', androidAt) + 1
source = `${source.slice(0, androidBraceEnd)}${SIGNING_CONFIG}${source.slice(androidBraceEnd)}`

// 3. Point the release build type at it.
const releaseBlock = /getByName\("release"\)\s*\{/.exec(source)
if (!releaseBlock) fail('the `getByName("release")` build type')
const insertAt = releaseBlock.index + releaseBlock[0].length
source = `${source.slice(0, insertAt)}\n            signingConfig = signingConfigs.getByName("release")${source.slice(insertAt)}`

fs.writeFileSync(gradleFile, source)
console.log(`patch-android-signing: release signing configured in ${path.relative(process.cwd(), gradleFile)}`)
