/**
 * Teaches the generated Android Gradle project to sign release builds with the
 * project keystore (AP-7, C-30).
 *
 * `src-tauri/gen/android/` is build output, regenerated by `tauri android init`
 * on every CI run, so this patch has to be reapplied each time rather than
 * committed. It is idempotent and fails loudly when the Tauri template changes
 * shape — a silently unsigned APK cannot install over the previous version,
 * which would break every user's upgrade path without any error at build time.
 *
 * Reads `src-tauri/gen/android/keystore.properties` at build time:
 *
 *     storeFile=release.jks
 *     storePassword=…
 *     keyAlias=…
 *     password=…
 *
 * `storeFile` is resolved against `gen/android/` (the Gradle *root* project),
 * not `gen/android/app/`, which is where the release workflow writes the
 * keystore.
 *
 *     node scripts/patch-android-signing.ts
 */

import fs from 'node:fs'
import path from 'node:path'

const gradleFile = path.resolve('src-tauri/gen/android/app/build.gradle.kts')

if (!fs.existsSync(gradleFile)) {
  console.error(`patch-android-signing: ${gradleFile} not found — run \`tauri android init\` first`)
  process.exit(1)
}

let source = fs.readFileSync(gradleFile, 'utf8')

if (source.includes('signingConfigs.getByName("release")')) {
  console.log('patch-android-signing: already patched')
  process.exit(0)
}

/**
 * The template already imports `java.util.Properties` to read `tauri.properties`.
 * Importing it a second time is not a warning in Kotlin script — it is a hard
 * "imported name 'Properties' is ambiguous" compile error — so only add what is
 * genuinely missing. `Properties.load` takes any InputStream, so using
 * `File.inputStream()` avoids needing `java.io.FileInputStream` at all.
 */
const REQUIRED_IMPORTS = ['import java.util.Properties']

const SIGNING_CONFIG = `
    signingConfigs {
        create("release") {
            // Written by the release workflow next to this Gradle root project.
            val keystorePropertiesFile = rootProject.file("keystore.properties")
            if (!keystorePropertiesFile.exists()) {
                throw GradleException(
                    "keystore.properties not found in \${rootProject.projectDir}. " +
                        "A release APK must be signed with the project keystore (C-30)."
                )
            }
            val keystoreProperties = Properties()
            keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
            keyAlias = keystoreProperties.getProperty("keyAlias")
            keyPassword = keystoreProperties.getProperty("password")
            storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
            storePassword = keystoreProperties.getProperty("storePassword")
        }
    }
`

function fail(what: string): never {
  console.error(`patch-android-signing: could not find ${what} in ${gradleFile}.`)
  console.error('The Tauri Android template has changed; update this script before releasing.')
  process.exit(1)
}

// 1. Add only the imports the template does not already have, at the very top.
const missingImports = REQUIRED_IMPORTS.filter(
  (statement) => !new RegExp(`^\\s*${statement.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*$`, 'm').test(source),
)
if (missingImports.length > 0) {
  source = `${missingImports.join('\n')}\n${source}`
}

// 2. The signing config itself, just inside `android { … }`.
const androidAt = source.indexOf('\nandroid {')
if (androidAt < 0) fail('the `android {` block')
const androidBraceEnd = source.indexOf('{', androidAt) + 1
source = `${source.slice(0, androidBraceEnd)}${SIGNING_CONFIG}${source.slice(androidBraceEnd)}`

// 3. Point the release build type at it.
const releaseBlock = /getByName\("release"\)\s*\{/.exec(source)
if (!releaseBlock) fail('the `getByName("release")` build type')
const insertAt = releaseBlock.index + releaseBlock[0].length
source = `${source.slice(0, insertAt)}\n            signingConfig = signingConfigs.getByName("release")${source.slice(insertAt)}`

fs.writeFileSync(gradleFile, source)
console.log(`patch-android-signing: release signing configured in ${path.relative(process.cwd(), gradleFile)}`)
